### ISSUE TITLE
Add Angular Material

### ISSUE THREAD

**Issue by JamesGabby** [JamesGabby/artemas#1]
## TODO

- [ ] Add angular material
- [ ] Create a home component
- [ ] Add side navigation (fixed)
- [ ] Add top toolbar (fixed)
